export const turfs = [
  {
    id: 1,
    name: "GreenField Arena",
    type: "Football",
    location: "Central Park, NY",
    price: 1500,
    rating: 4.5,
    availableHours: "9:00 AM - 10:00 PM",
    image: "/football.avif",
    size: "standard",
  },
  {
    id: 2,
    name: "City Sports Center",
    type: "Basketball",
    location: "Downtown LA",
    price: 1200,
    rating: 4.2,
    availableHours: "8:00 AM - 11:00 PM",
    image: "/basketball.avif",
    size: "standard",
  },
  {
    id: 3,
    name: "Tennis World",
    type: "Tennis",
    location: "Miami Beach, FL",
    price: 1000,
    rating: 4.0,
    availableHours: "7:00 AM - 9:00 PM",
    image: "/tennis.avif",
    size: "small",
  },
  {
    id: 4,
    name: "Golden Golf Club",
    type: "Golf",
    location: "Scottsdale, AZ",
    price: 2000,
    rating: 4.7,
    availableHours: "6:00 AM - 8:00 PM",
    image: "/golf.avif",
    size: "large",
  },
  {
    id: 5,
    name: "Ice Palace",
    type: "Ice Hockey",
    location: "Aspen, CO",
    price: 1800,
    rating: 4.6,
    availableHours: "10:00 AM - 12:00 AM",
    image: "/icehockey.avif",
    size: "standard",
  },
  {
    id: 6,
    name: "Cricket Grounds",
    type: "Cricket",
    location: "London, UK",
    price: 1600,
    rating: 4.4,
    availableHours: "9:00 AM - 9:00 PM",
    image: "/cricket.avif",
    size: "large",
  },
  {
    id: 7,
    name: "Rugby Park",
    type: "Rugby",
    location: "Sydney, AU",
    price: 1400,
    rating: 4.3,
    availableHours: "8:00 AM - 10:00 PM",
    image: "/rugby.avif",
    size: "standard",
  },
  {
    id: 8,
    name: "Baseball Field",
    type: "Baseball",
    location: "New York, USA",
    price: 1300,
    rating: 4.1,
    availableHours: "7:00 AM - 11:00 PM",
    image: "/baseball.avif",
    size: "standard",
  },
  {
    id: 9,
    name: "Swimming Pool",
    type: "Swimming",
    location: "Los Angeles, USA",
    price: 1100,
    rating: 3.9,
    availableHours: "6:00 AM - 10:00 PM",
    image: "/swimming.avif",
    size: "small",
  },
  {
    id: 10,
    name: "Volleyball Court",
    type: "Volleyball",
    location: "Miami, USA",
    price: 900,
    rating: 3.8,
    availableHours: "10:00 AM - 8:00 PM",
    image: "/volleyball.avif",
    size: "small",
  },
  {
    id: 11,
    name: "Athletics Track",
    type: "Athletics",
    location: "London, UK",
    price: 1700,
    rating: 4.8,
    availableHours: "8:00 AM - 7:00 PM",
    image: "/athletics.avif",
    size: "large",
  },
  {
    id: 12,
    name: "Badminton Court",
    type: "Badminton",
    location: "Sydney, AU",
    price: 800,
    rating: 3.7,
    availableHours: "9:00 AM - 11:00 PM",
    image: "/badminton.avif",
    size: "small",
  },
]

